In [3]:
import pandas as pd
import numpy as np

In [4]:
#Load all five datasets ( sales.csv , products.csv , stores.csv , category.csv , warranty.csv ) into separate Pandas DataFrames

In [5]:
sales = pd.read_csv("../../../Data/sales.csv")
products = pd.read_csv("../../../Data/products.csv")
stores = pd.read_csv("../../../Data/stores.csv")
category = pd.read_csv("../../../Data/category.csv")
warranty = pd.read_csv("../../../Data/warranty.csv")

In [6]:
# Display the first 10 records, last 10 records, shape, columns, and data types of every dataset

In [7]:
print(sales.head(10))
print(sales.tail(10))

      sale_id   sale_date store_id product_id  quantity
0  OID-358365  2021-09-16    ST-33       P-44         1
1  OID-358510  2022-01-28    ST-33       P-44         1
2  OID-358525  2021-11-26    ST-33       P-44         1
3  OID-358591  2021-09-15    ST-33       P-44         1
4  OID-358601  2022-02-07    ST-33       P-44         1
5  OID-358877  2022-03-10    ST-33       P-44         1
6  OID-358995  2022-04-05    ST-33       P-44         1
7  OID-358996  2021-11-22    ST-33       P-44         1
8  OID-359012  2022-03-28    ST-33       P-44         1
9  OID-359013  2022-02-08    ST-33       P-44         1
            sale_id   sale_date store_id product_id  quantity
1040181  OID-358346  2022-05-31    ST-33       P-47         1
1040182  OID-358347  2022-06-21    ST-33       P-48         1
1040183  OID-358348  2022-07-04    ST-33       P-48         1
1040184  OID-358349  2022-08-13    ST-33       P-48         1
1040185  OID-358350  2022-02-16    ST-33       P-48         1
1040186  OID-358351  2022-08-11    ST-33       P-48         1
1040187  OID-358352  2022-02-06    ST-33       P-49         1
1040188  OID-358353  2022-05-27    ST-33       P-49         1
1040189  OID-358354  2022-03-22    ST-33       P-49         1
1040190  OID-358355  2022-07-19    ST-33       P-49         1

In [8]:
sales.shape

(1040191, 5)

In [9]:
sales.columns

Index(['sale_id', 'sale_date', 'store_id', 'product_id', 'quantity'], dtype='object')

In [10]:
sales.dtypes

sale_id       object
sale_date     object
store_id      object
product_id    object
quantity       int64
dtype: object

In [11]:
# Create a summary table showing the number of rows, columns, missing values, and memory usage for each dataset.

In [16]:
print(sales.shape[0])
sales.shape[1]

1040191

5

In [23]:
sales.isnull().sum().sum() 

# 1st sum()  -> Count missing values in each column
# 2nd sum()  -> Add all column counts to get total missing values

0

In [25]:
sales.memory_usage()

Index             132
sale_id       8321528
sale_date     8321528
store_id      8321528
product_id    8321528
quantity      8321528
dtype: int64

In [29]:
summary = pd.DataFrame()

# Add dataset names
summary["Dataset"] = ["Sales", "Products", "Stores", "Category", "Warranty"]

# Add total rows
summary["Rows"] = [
    sales.shape[0],
    products.shape[0],
    stores.shape[0],
    category.shape[0],
    warranty.shape[0]
]

# Add total columns
summary["Columns"] = [
    sales.shape[1],
    products.shape[1],
    stores.shape[1],
    category.shape[1],
    warranty.shape[1]
]

# Add total missing values
summary["Missing Values"] = [
    sales.isnull().sum().sum(),       # Column-wise Missing -> Total Missing
    products.isnull().sum().sum(),
    stores.isnull().sum().sum(),
    category.isnull().sum().sum(),
    warranty.isnull().sum().sum()
]

# Add total memory usage
summary["Memory Usage (Bytes)"] = [
    sales.memory_usage(deep=True).sum(),       # Memory of all columns
    products.memory_usage(deep=True).sum(),
    stores.memory_usage(deep=True).sum(),
    category.memory_usage(deep=True).sum(),
    warranty.memory_usage(deep=True).sum()
]

# Display final report
summary

    Dataset     Rows  Columns  Missing Values  Memory Usage (Bytes)
0     Sales  1040191        5               0             242004109
1  Products       64        5               0                 15420
2    Stores       73        4               0                 17038
3  Category       10        2               0                  1263
4  Warranty    30836        4               0               7296509

In [33]:
# Create a DataFrame report identifying each dataset as either a Fact Table or Dimension Table, along with its business purpose.

In [36]:
table_info = pd.DataFrame()

# Table Name

table_info['Table'] = [
    "sales",
    "products",
    "stores",
    "category",
    "warranty"
]

# Table Type

table_info['Type'] = [
    "Fact",
    "Dimension",
    "Dimension",
    "Dimension",
    "Dimension"
]

# Table Purpose

table_info["Purpose"] = [
    "Stores all sales transactions",
    "Stores product details",
    "Stores store information",
    "Stores product category details",
    "Stores warranty claim information"
]

# Display report 

table_info

      Table       Type                            Purpose
0     sales       Fact      Stores all sales transactions
1  products  Dimension             Stores product details
2    stores  Dimension           Stores store information
3  category  Dimension    Stores product category details
4  warranty  Dimension  Stores warranty claim information

In [38]:
# Prepare a professional Dataset Overview Report containing dataset name, row count, column count, primary key, foreign keys, and business purpose of each table.

In [44]:
print(sales.columns)
print(stores.columns)
print(warranty.columns)
print(products.columns)
print(category.columns)

Index(['sale_id', 'sale_date', 'store_id', 'product_id', 'quantity'], dtype='object')
Index(['store_id', 'store_name', 'city', 'country'], dtype='object')
Index(['claim_id', 'claim_date', 'sale_id', 'claim_status'], dtype='object')
Index(['product_id', 'product_name', 'category_id', 'launch_date', 'price'], dtype='object')
Index(['category_id', 'category_name'], dtype='object')

In [45]:
report = pd.DataFrame()

# Add dataset names
report["Dataset"] = [
    "Sales",
    "Products",
    "Stores",
    "Category",
    "Warranty"
]

# Add total rows
report["Rows"] = [
    sales.shape[0],
    products.shape[0],
    stores.shape[0],
    category.shape[0],
    warranty.shape[0]
]

# Add total columns
report["Columns"] = [
    sales.shape[1],
    products.shape[1],
    stores.shape[1],
    category.shape[1],
    warranty.shape[1]
]

# Add Primary Key
report["Primary Key"] = [
    "sale_id",
    "product_id",
    "store_id",
    "category_id",
    "claim_id"
]

# Add Foreign Keys
report["Foreign Keys"] = [
    "product_id, store_id",
    "category_id",
    "-",
    "-",
    "sale_id"
]

# Add business purpose
report["Purpose"] = [
    "Stores all sales transactions",
    "Stores product details",
    "Stores store details",
    "Stores product category details",
    "Stores warranty claim details"
]

# Display final report
report

,Dataset,Rows,Columns,Primary Key,Foreign Keys,Purpose
0,Sales,1040191,5,sale_id,"product_id, store_id",Stores all sales transactions
1,Products,64,5,product_id,category_id,Stores product details
2,Stores,73,4,store_id,-,Stores store details
3,Category,10,2,category_id,-,Stores product category details
4,Warranty,30836,4,claim_id,sale_id,Stores warranty claim details

In [1]:
# Business Insight:
# The Sales table is the central transaction (Fact) table, while Products,
# Stores, Category, and Warranty are Dimension tables that enrich sales data
# for business reporting and analysis.