In [2]:
import pandas as pd
import numpy as np

In [3]:
sales = pd.read_csv("../../../Data/sales.csv")
products = pd.read_csv("../../../Data/products.csv")
stores = pd.read_csv("../../../Data/stores.csv")
category = pd.read_csv("../../../Data/category.csv")
warranty = pd.read_csv("../../../Data/warranty.csv")

# Display all products having a Price greater than ₹1000

In [5]:
products[products["price"] > 1000]

   product_id                   product_name category_id launch_date  price
0         P-1        MacBook Pro (Touch Bar)       CAT-1  01-10-2016   1499
4         P-5    MacBook Pro (13-inch, 2017)       CAT-1  01-06-2017   1299
5         P-6                 MacBook (2017)       CAT-1  01-06-2017   1299
14       P-15                  iPhone XS Max       CAT-4  01-09-2018   1099
16       P-17     MacBook Air (Retina, 2018)       CAT-1  01-10-2018   1199
22       P-23              iPhone 11 Pro Max       CAT-4  01-09-2019   1099
29       P-30      MacBook Pro (M1, 13-inch)       CAT-1  01-11-2020   1299
33       P-34              iPhone 12 Pro Max       CAT-4  01-11-2020   1099
37       P-38       iPad Pro (M1, 12.9-inch)       CAT-3  01-04-2021   1099
38       P-39             iMac (24-inch, M1)       CAT-7  01-04-2021   1299
44       P-45              iPhone 13 Pro Max       CAT-4  01-09-2021   1099
47       P-48  MacBook Pro (M1 Pro, 14-inch)       CAT-1  01-10-2021   1999
48       P-49  MacBook Pro (M1 Max, 16-inch)       CAT-1  01-10-2021   2499
52       P-53                     Mac Studio       CAT-7  01-03-2022   1999
60       P-61       iPad Pro (M2, 12.9-inch)       CAT-3  01-10-2022   1099
63       P-64              iPhone 15 Pro Max       CAT-4  01-09-2023   1199

# Display all sales where Quantity is greater than 2.

In [7]:
sales[sales["quantity"] > 2]

            sale_id   sale_date store_id product_id  quantity
10536    OID-398209  2019-10-23    ST-30       P-23         3
10539    OID-398231  2020-03-15    ST-30       P-20         3
10548    OID-398277  2020-02-10    ST-30       P-22         3
10550    OID-398279  2019-12-21    ST-30       P-24         3
10551    OID-398289  2020-02-10    ST-30       P-24         3
...             ...         ...      ...        ...       ...
917391  OID-1048538  2019-01-05     ST-1       P-16         3
917392  OID-1048540  2019-01-04     ST-1       P-11         3
917397  OID-1048545  2019-01-02     ST-1       P-11         3
917398  OID-1048546  2019-01-02     ST-1       P-11         3
917402  OID-1048550  2019-01-02     ST-1       P-16         3

[49118 rows x 5 columns]

# Display all warranty claims whose status is "Free Replaced".

In [19]:
warranty[warranty["claim_status"] == "Free Replaced"]

       claim_id  claim_date     sale_id   claim_status
0        CL-285  17-01-2020  OID-363381  Free Replaced
1        CL-290  19-01-2020  OID-363359  Free Replaced
2        CL-291  19-01-2020  OID-363371  Free Replaced
3        CL-299  21-01-2020  OID-363397  Free Replaced
4        CL-308  23-01-2020  OID-363395  Free Replaced
...         ...         ...         ...            ...
30831  CL-14178  16-02-2023  OID-358351  Free Replaced
30832  CL-15003  28-05-2022  OID-358352  Free Replaced
30833  CL-16934  24-08-2022  OID-358353  Free Replaced
30834  CL-12714  28-09-2022  OID-358354  Free Replaced
30835  CL-12913  09-10-2022  OID-358355  Free Replaced

[20167 rows x 4 columns]

In [20]:
warranty["claim_status"].unique() # to get all the unique values in the claim_status column.

array(['Free Replaced', 'Paid Repaired', 'Warranty Void'], dtype=object)

# Display all stores located in USA.

In [22]:
stores[stores["country"] == "USA"]

  store_id                store_name           city country
0     ST-1        Apple Fifth Avenue       New York     USA
1     ST-2        Apple Union Square  San Francisco     USA
2     ST-3     Apple Michigan Avenue        Chicago     USA
3     ST-4           Apple The Grove    Los Angeles     USA
4     ST-5   Apple South Coast Plaza     Costa Mesa     USA
5     ST-6          Apple Scottsdale     Scottsdale     USA
6     ST-7     Apple Mall of America    Bloomington     USA
7     ST-8       Apple Eastview Mall         Victor     USA
8     ST-9  Apple Lennox Town Center       Columbus     USA
9    ST-10       Apple Tysons Corner         Tysons     USA

# Prepare a filtered dataset showing Premium Apple products sold only through UK stores with complete store and product information.

In [25]:
sales_products = sales.merge(
    products,
    on="product_id"
)

sales_products_store = sales_products.merge(
    stores,
    on="store_id"
)

premium_UK = sales_products_store[
    (sales_products_store["price"] > 1000)
    &
    (sales_products_store["country"] == "UK")
]

premium_UK

,sale_id,sale_date,store_id,product_id,quantity,product_name,category_id,launch_date,price,store_name,city,country
42857,OID-471364,2023-09-12,ST-24,P-64,1,iPhone 15 Pro Max,CAT-4,01-09-2023,1199,Apple Bluewater,Greenhithe,UK
42872,OID-471379,2024-01-16,ST-24,P-64,1,iPhone 15 Pro Max,CAT-4,01-09-2023,1199,Apple Bluewater,Greenhithe,UK
42875,OID-471382,2023-09-26,ST-24,P-64,1,iPhone 15 Pro Max,CAT-4,01-09-2023,1199,Apple Bluewater,Greenhithe,UK
42879,OID-471386,2023-12-01,ST-24,P-64,1,iPhone 15 Pro Max,CAT-4,01-09-2023,1199,Apple Bluewater,Greenhithe,UK
42880,OID-471387,2023-09-10,ST-24,P-64,1,iPhone 15 Pro Max,CAT-4,01-09-2023,1199,Apple Bluewater,Greenhithe,UK
...,...,...,...,...,...,...,...,...,...,...,...,...
923255,OID-2709,2024-02-28,ST-67,P-64,1,iPhone 15 Pro Max,CAT-4,01-09-2023,1199,Apple Birmingham,Birmingham,UK
923257,OID-2711,2024-01-01,ST-67,P-64,1,iPhone 15 Pro Max,CAT-4,01-09-2023,1199,Apple Birmingham,Birmingham,UK
923261,OID-2715,2024-02-05,ST-67,P-64,1,iPhone 15 Pro Max,CAT-4,01-09-2023,1199,Apple Birmingham,Birmingham,UK
923267,OID-2721,2024-06-26,ST-67,P-64,1,iPhone 15 Pro Max,CAT-4,01-09-2023,1199,Apple Birmingham,Birmingham,UK
923270,OID-2724,2024-05-21,ST-67,P-64,1,iPhone 15 Pro Max,CAT-4,01-09-2023,1199,Apple Birmingham,Birmingham,UK

# Business Insight:
# Business filtering allows organizations to identify high-value products,
# specific customer segments, and regional performance for better decisions.