In [1]:
import pandas as pd
import numpy as np

In [36]:
sales = pd.read_csv("../../../Data/sales.csv")
products = pd.read_csv("../../../Data/products.csv")
stores = pd.read_csv("../../../Data/stores.csv")
category = pd.read_csv("../../../Data/category.csv")
warranty = pd.read_csv("../../../Data/warranty.csv")

Convert all Product Names into uppercase.

In [37]:
products["product_name"] = products["product_name"].str.upper()

Remove extra spaces from all text columns wherever applicable.

In [38]:
stores["store_name"] = stores["store_name"].str.strip()

stores["city"] = stores["city"].str.strip()

stores["country"] = stores["country"].str.strip()

Find all products whose names contain the word "iPhone"

In [39]:
products[
    products["product_name"].str.contains("iphone", case=False)
]

# Case = False because it will match any case sensitive word like "iPhone", "IPHONE" , "iphone"

   product_id         product_name category_id launch_date  price
6         P-7             IPHONE 8       CAT-4  01-09-2017    699
7         P-8        IPHONE 8 PLUS       CAT-4  01-09-2017    799
10       P-11             IPHONE X       CAT-4  01-11-2017    999
13       P-14            IPHONE XS       CAT-4  01-09-2018    999
14       P-15        IPHONE XS MAX       CAT-4  01-09-2018   1099
15       P-16            IPHONE XR       CAT-4  01-10-2018    749
20       P-21            IPHONE 11       CAT-4  01-09-2019    699
21       P-22        IPHONE 11 PRO       CAT-4  01-09-2019    999
22       P-23    IPHONE 11 PRO MAX       CAT-4  01-09-2019   1099
26       P-27            IPHONE 12       CAT-4  01-10-2020    799
27       P-28        IPHONE 12 PRO       CAT-4  01-10-2020    999
32       P-33       IPHONE 12 MINI       CAT-4  01-11-2020    699
33       P-34    IPHONE 12 PRO MAX       CAT-4  01-11-2020   1099
41       P-42        IPHONE 13 PRO       CAT-4  01-09-2021    999
42       P-43            IPHONE 13       CAT-4  01-09-2021    699
43       P-44       IPHONE 13 MINI       CAT-4  01-09-2021    699
44       P-45    IPHONE 13 PRO MAX       CAT-4  01-09-2021   1099
50       P-51  IPHONE SE (3RD GEN)       CAT-4  01-03-2022    429
53       P-54        IPHONE 14 PRO       CAT-4  01-09-2022    999
54       P-55            IPHONE 14       CAT-4  01-09-2022    799
61       P-62            IPHONE 15       CAT-4  01-09-2023    799
62       P-63        IPHONE 15 PRO       CAT-4  01-09-2023    999
63       P-64    IPHONE 15 PRO MAX       CAT-4  01-09-2023   1199

Replace the word "IPHONE" with "APPLE" in the Product Name column.

In [40]:
products["product_name"] = products["product_name"].str.replace("IPHONE","APPLE",case = False)

In [41]:
print(products)

   product_id                   product_name category_id launch_date  price
0         P-1        MACBOOK PRO (TOUCH BAR)       CAT-1  01-10-2016   1499
1         P-2                        AIRPODS       CAT-2  01-12-2016    159
2         P-3           IPAD PRO (10.5-INCH)       CAT-3  01-06-2017    649
3         P-4  IPAD PRO (12.9-INCH, 2ND GEN)       CAT-3  01-06-2017    799
4         P-5    MACBOOK PRO (13-INCH, 2017)       CAT-1  01-06-2017   1299
..        ...                            ...         ...         ...    ...
59       P-60         IPAD PRO (M2, 11-INCH)       CAT-3  01-10-2022    799
60       P-61       IPAD PRO (M2, 12.9-INCH)       CAT-3  01-10-2022   1099
61       P-62                       APPLE 15       CAT-4  01-09-2023    799
62       P-63                   APPLE 15 PRO       CAT-4  01-09-2023    999
63       P-64               APPLE 15 PRO MAX       CAT-4  01-09-2023   1199

[64 rows x 5 columns]

Create a searchable Product Catalog containing Product Name, Category, Price, and Launch Date
sorted alphabetically

In [35]:
product_catalog = products.merge(
    category,
    on="category_id"
)

product_catalog = product_catalog[
    [
        "product_name",
        "category_name",
        "price",
        "launch_date"
    ]
]

product_catalog = product_catalog.sort_values(
    by="product_name"
)

product_catalog

                     product_name         category_name  price launch_date
34                  AAPL FITNESS+  Subscription Service    120  01-12-2020
25                       AAPL ONE  Subscription Service    179  01-10-2020
9                      AAPL TV 4K      Streaming Device    179  01-09-2017
40                     AAPL TV 4K      Streaming Device    179  01-04-2021
56        AAPL WATCH SE (2ND GEN)              Wearable    249  01-09-2022
..                            ...                   ...    ...         ...
4     MACBOOK PRO (13-INCH, 2017)                Laptop   1299  01-06-2017
48  MACBOOK PRO (M1 MAX, 16-INCH)                Laptop   2499  01-10-2021
47  MACBOOK PRO (M1 PRO, 14-INCH)                Laptop   1999  01-10-2021
29      MACBOOK PRO (M1, 13-INCH)                Laptop   1299  01-11-2020
0         MACBOOK PRO (TOUCH BAR)                Laptop   1499  01-10-2016

[64 rows x 4 columns]

# Business Insight:
Well-formatted text data enables efficient searching,

consistent reporting, and better customer-facing analytics.