In [1]:
import pandas as pd
import numpy as np

In [2]:
sales = pd.read_csv("../../../Data/sales.csv")
products = pd.read_csv("../../../Data/products.csv")
stores = pd.read_csv("../../../Data/stores.csv")
category = pd.read_csv("../../../Data/category.csv")
warranty = pd.read_csv("../../../Data/warranty.csv")

Calculate the Total Quantity Sold for every Product.

In [6]:
product_sales = (sales
                 .groupby("product_id")
                 .agg(
                     total_quantity = ("quantity", "sum")
                      )
                      .reset_index()
                      )

product_sales

   product_id  total_quantity
0         P-1            5119
1        P-10            5209
2        P-11           78607
3        P-12           28931
4        P-13           28176
..        ...             ...
59       P-63           21958
60       P-64           21784
61        P-7            5178
62        P-8            5134
63        P-9            5306

[64 rows x 2 columns]

Count the total number of products available in each Category.

In [7]:
category_products = (
    products.groupby("category_id")
    .agg(
        total_products = ("product_id", "count")
    )
    .reset_index()
)

category_products

  category_id  total_products
0       CAT-1               8
1      CAT-10               1
2       CAT-2               5
3       CAT-3              12
4       CAT-4              23
5       CAT-5               6
6       CAT-6               2
7       CAT-7               4
8       CAT-8               2
9       CAT-9               1

Find the total number of sales handled by every Store.

In [11]:
store_sales = (sales
               .groupby("store_id")
               .agg(total_sales = ("sale_id", "count")
                    )
                    .reset_index()
               )

store_sales

   store_id  total_sales
0      ST-1        34828
1     ST-10        23310
2     ST-11        23435
3     ST-12        23728
4     ST-13        23388
..      ...          ...
65    ST-69          647
66     ST-7        23329
67    ST-70          685
68     ST-8        23421
69     ST-9        23546

[70 rows x 2 columns]

Calculate the Average Quantity Sold by each Country.

In [15]:
country_sales = (
    sales.merge(stores, on = "store_id")
    .groupby("country")
    .agg(
        avg_sales = ("quantity" , "mean")
         )
         .reset_index()
         )
print(country_sales)

               country  avg_sales
0            Argentina   1.000000
1            Australia   1.051906
2              Bolivia   1.000000
3               Brazil   1.050526
4               Canada   1.192969
5                Chile   1.082015
6                China   1.077081
7           Costa Rica   1.000000
8   Dominican Republic   1.000000
9               France   1.146658
10             Germany   1.113926
11               India   1.032312
12           Indonesia   1.077806
13               Italy   1.148610
14               Japan   1.113709
15            Malaysia   1.080882
16              Mexico   1.047735
17         Netherlands   1.154497
18                Peru   1.000000
19         Philippines   1.000000
20               Qatar   1.000000
21        Saudi Arabia   1.000000
22           Singapore   1.091141
23         South Korea   1.036222
24               Spain   1.057194
25         Switzerland   1.049443
26              Taiwan   1.070966
27            Thailand   1.075731
28              Turkey   1.020138
29                 UAE   1.066431
30                  UK   1.088199
31                 USA   1.263889
32             Uruguay   1.000000
33           Venezuela   1.000000
34             Vietnam   1.000000

Prepare a Store Performance Report containing Store Name, Country, Total Sales Records, Total
Quantity Sold, and Average Quantity Sold.

In [21]:
store_performance = (
    sales.merge(stores,on = "store_id")
                    .groupby(["store_name", "country"])
                    .agg(
                        total_sales = ("sale_id","count"),
                         total_quantity_Sold = ("quantity","sum"),
                         average_quantity_sold =("quantity","mean")
                         )
                         .reset_index()
                         )
store_performance

,store_name,country,total_sales,total_quantity_Sold,average_quantity_sold
0,Apple Amsterdam,Netherlands,12874,14863,1.154497
1,Apple Ankara,Turkey,26672,27229,1.020883
2,Apple Bangkok,Thailand,7553,8125,1.075731
3,Apple Barcelona,Spain,9321,9918,1.064049
4,Apple Beijing,China,7537,8113,1.076423
...,...,...,...,...,...
65,Apple Tysons Corner,USA,23310,29215,1.253325
66,Apple Union Square,USA,35044,44395,1.266836
67,Apple West Edmonton Mall,Canada,17304,19143,1.106276
68,Apple Yorkdale,Canada,23728,29882,1.259356
69,Apple Zurich,Switzerland,11488,12056,1.049443

# Business Insight:
Store-wise performance helps evaluate sales,
quantity sold, and average customer purchase behavior.